apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-rabbitmq
spec:
  selector:
    matchLabels:
      app: producer-rabbitmq
  template:
    metadata:
      labels:
        app: producer-rabbitmq
    spec:
      containers:
      - name: producer-rabbitmq
        image: nimisha78/producer88-rabbit:1.0
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: producer-rabbitmq
spec:
  type: NodePort
  selector:
    app: producer-rabbitmq
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 31500


